### PR TITLE
Activated code coverage

### PR DESCRIPTION
**Pull request by SebastianSchuetze**
# PR Summary

This is to check whether Pester is still slow with code coverage.

#262 is related.

## PR Checklist

- [ ] [Write Help](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-help)
- [ ] [Write Unit Test](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-unit-test)
- [ ] [Update CHANGELOG.md](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#update-changelogmd)

### CODE REVIEW

**Comment by SebastianSchuetze** [comment]
I made a test and basically switched the PowerShell task to use PowerShell core. 

You can see the difference when using PS 5 on windows takes roughly 24 minutes (whole pipeline 28 minutes)
https://loecda.visualstudio.com/Team%20Module/_build/results?buildId=1872&view=logs&j=df7cdcec-8c9a-591d-7383-990f35cfc117&t=1ad5f601-14eb-5211-34b7-3146063ec0a0

the same with PS core takes only around 10 minutes (whole pipeline 16 minutes) on the same machine:
https://loecda.visualstudio.com/Team%20Module/_build/results?buildId=1873&view=logs&j=df7cdcec-8c9a-591d-7383-990f35cfc117&t=1ad5f601-14eb-5211-34b7-3146063ec0a0

Do you think it that is fast enough again @DarqueWarrior? How long did it take before the bug?

**Comment by SebastianSchuetze** [comment]
I changed it to only have code coverage on the windows machine.

**Comment by SebastianSchuetze** [comment]
@DarqueWarrior what do you say? Is the time enough to turn it on again?

**Comment by DarqueWarrior** [comment]
It is still really slow. I have been testing locally.

**Comment by DarqueWarrior** [comment]
The windows build already takes the longest. Wonder if it would not make sense to enable on one of the other platforms instead so they can be running at the same time.

**Comment by SebastianSchuetze** [comment]
For pester there is an open issue or the plan to separate test on to multiple processes or agents. Not sure how far they are that would speed up things!

As for running the tests on another agent, we could do it. I will modify this PR and switch it to a Mac OS agent. I made tests in the past and Mac OS seemed always the fastest to me.

**Comment by SebastianSchuetze** [comment]
@DarqueWarrior as you can see I ran the code coverage on mac and Unix in parallel.
They even took a bit longer around 20 minutes. So this is not faster, but I got an idea of how to maybe solve it, but it is a bit of effort. Look at  the following graphic

image

So we would split the unit tests into subfolders within the pipeline (not in the repo) dynamically by a divisor X of the number of unit test files.
Then we run multiple unit tests in parallel, collect the results, merge them and then commit them.

What do you say? Too much effort or manageable?

**Comment by DarqueWarrior** [comment]
How much faster do you think this will make it?

**Comment by SebastianSchuetze** [comment]
How much it speeds up depends on the following parameters:
* how many agents can we run maximum in parallel:
  * one for mac
  * one for Unix
  * 8 left for code coverage testing with unit tests

If we expect that only one build pipeline instance is running at a certain point in time. I would generally expect that there are not more than 2 at the same time with the current workload.

I would suggest dividing the workload by at least 4 parallel agents in a [YAML loop on job level](https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/each-expression.md). But how long each package needs really depends on the number of unit tests per file. I would only simply divide the number of unit test files by X and then put them in subfolders.

We also have some overhead for each job, since we have to install all the needed modules every time (e.g. Pester).

In the best case, it would then be around 3 minutes for all agents and in worst case 5 minutes for all. It would get better when we use more agents.

I could give it a try and prototype something.

**Comment by DarqueWarrior** [comment]
The performance is still too slow.

**Pull request closed without merging**
